import Navigation from '@/components/Navigation' 
import Footer from '@/components/Footer'
import './globals.css'


export const metadata = {
  title: 'PrimerApp',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navigation></Navigation>
        {children}
        <Footer></Footer>
        </body>
    </html>
  )
}
