
import './globals.css';
import { Inter } from 'next/font/google';
import Navigation from './Nav/Navigation.jsx';
import Footer from '../components/Foooter/Footer';
import { createIconsTypes } from '@/utils/createIcons';

const inter = Inter({ subsets: ['latin'] });


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>DaleQueValen</title>
      </head>


      {/* <Navigation/> */}
      <body className='lg:pr-[140px] lg:pl-[140px] ms:pr-[15px] ms:pl-[15px]'>
        <Navigation/>
          {children}
        {<Footer/>}
      </body>
    </html>
  );
}
